MACHINE LEARNING ASSIGNMENT

In [66]:
import pandas as pd
data=pd.read_csv("HCV-Egy-Data.csv")
data

,Age,Gender,BMI,Fever,Nausea/Vomting,Headache,Diarrhea,Fatigue & generalized bone ache,Jaundice,Epigastric pain,...,ALT 36,ALT 48,ALT after 24 w,RNA Base,RNA 4,RNA 12,RNA EOT,RNA EF,Baseline histological Grading,Baselinehistological staging
0,56,1,35,2,1,1,1,2,2,2,...,5,5,5,655330,634536,288194,5,5,13,2
1,46,1,29,1,2,2,1,2,2,1,...,57,123,44,40620,538635,637056,336804,31085,4,2
2,57,1,33,2,2,2,2,1,1,1,...,5,5,5,571148,661346,5,735945,558829,4,4
3,49,2,33,1,2,1,2,1,2,1,...,48,77,33,1041941,449939,585688,744463,582301,10,3
4,59,1,32,1,1,2,1,2,2,2,...,94,90,30,660410,738756,3731527,338946,242861,11,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1380,44,1,29,1,2,2,2,1,1,1,...,63,44,45,387795,55938,5,5,5,15,4
1381,55,1,34,1,2,2,1,1,1,1,...,97,64,41,481378,152961,393339,73574,236273,10,2
1382,42,1,26,2,2,1,1,1,2,1,...,87,39,24,612664,572756,806109,343719,160457,6,2
1383,52,1,29,2,1,1,2,2,2,1,...,48,81,43,139872,76161,515730,2460,696074,15,3
1384,55,2,26,1,2,2,2,1,2,1,...,64,71,34,1190577,628730,5,5,5,13,3

In [67]:
data.shape

(1385, 29)

In [68]:
data.isnull().sum()

Age                                 0
Gender                              0
BMI                                 0
Fever                               0
Nausea/Vomting                      0
Headache                            0
Diarrhea                            0
Fatigue & generalized bone ache     0
Jaundice                            0
Epigastric pain                     0
WBC                                 0
RBC                                 0
HGB                                 0
Plat                                0
AST 1                               0
ALT 1                               0
ALT4                                0
ALT 12                              0
ALT 24                              0
ALT 36                              0
ALT 48                              0
ALT after 24 w                      0
RNA Base                            0
RNA 4                               0
RNA 12                              0
RNA EOT                             0
RNA EF                              0
Baseline histological Grading       0
Baselinehistological staging        0
dtype: int64

In [69]:
x=data.iloc[:,:-1]
y=data['Baseline histological Grading']


from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=RandomForestClassifier(n_estimators=100)

model.fit(x_train,y_train)
y_pred=model.predict(x_test)

accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy:}")

confusion_matrix=confusion_matrix(y_test,y_pred)
print("confusion matrix:\n",confusion_matrix)

claasification_rep=classification_report(y_test,y_pred)
print("classification report:\n",claasification_rep)

joblib.dump(model, 'model.pkl')

Accuracy: 0.8844765342960289
confusion matrix:
 [[18  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 17  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2 16  4  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 17  1  1  0  0  0  0  0  0  0  0]
 [ 0  0  1  2 11  2  0  0  0  0  0  0  0  0]
 [ 0  0  1  1  2 14  2  0  0  0  0  0  0  0]
 [ 0  0  0  1  1  2 16  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  1 17  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  4 20  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 28  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 18]]
classification report:
               precision    recall  f1-score   support

           3       1.00      1.00      1.00        18
           4       0.85      0.89      0.87        19
           5       0.80      0.73      0.76        22
           6       0.68      0.85      0.76        20
           7       0.73      0.69      0.71        16
           8       0.74      0.70      0.72        20
           9       0.89      0.80      0.84        20
          10       0.93      1.00      0.96        13
          11       0.95      1.00      0.98        20
          12       0.81      0.89      0.85        19
          13       1.00      0.83      0.91        24
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        28
          16       1.00      1.00      1.00        18

    accuracy                           0.88       277
   macro avg       0.88      0.88      0.88       277
weighted avg       0.89      0.88      0.88       277

['model.pkl']

NAIVE_BAYES

In [70]:
x=data.iloc[:,:-1]
y=data['Baseline histological Grading']

In [71]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [73]:
model=GaussianNB()

model.fit(x_train,y_train)
y_pred=model.predict(x_test)

accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy:}")


claasification_rep=classification_report(y_test,y_pred)
print("classification report:\n",claasification_rep)

Accuracy: 0.11913357400722022
classification report:
               precision    recall  f1-score   support

           3       0.17      0.06      0.08        18
           4       0.05      0.05      0.05        19
           5       0.00      0.00      0.00        22
           6       0.07      0.05      0.06        20
           7       0.33      0.31      0.32        16
           8       0.14      0.15      0.14        20
           9       0.03      0.05      0.04        20
          10       0.00      0.00      0.00        13
          11       0.12      0.25      0.16        20
          12       0.00      0.00      0.00        19
          13       0.14      0.12      0.13        24
          14       0.04      0.05      0.05        20
          15       0.22      0.43      0.29        28
          16       0.00      0.00      0.00        18

    accuracy                           0.12       277
   macro avg       0.09      0.11      0.09       277
weighted avg       0.10      0.12      0.10       277

naive_bayes(MultinomialNB)

In [74]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [75]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [76]:
import numpy as np
model=MultinomialNB()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

accuracy=accuracy_score(y_pred,y_test)
print(f"Accuracy: {accuracy:}")

claasification_rep=classification_report(y_test,y_pred,zero_division=0)
print("classification report:\n",claasification_rep)

Accuracy: 0.07581227436823104
classification report:
               precision    recall  f1-score   support

           3       0.00      0.00      0.00        18
           4       0.00      0.00      0.00        19
           5       0.17      0.05      0.07        22
           6       0.00      0.00      0.00        20
           7       0.06      0.25      0.10        16
           8       0.00      0.00      0.00        20
           9       0.09      0.05      0.06        20
          10       0.00      0.00      0.00        13
          11       0.12      0.30      0.17        20
          12       0.00      0.00      0.00        19
          13       0.10      0.33      0.15        24
          14       0.07      0.05      0.06        20
          15       0.00      0.00      0.00        28
          16       0.00      0.00      0.00        18

    accuracy                           0.08       277
   macro avg       0.04      0.07      0.04       277
weighted avg       0.05      0.08      0.05       277

bernoullinb

In [77]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [80]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [81]:
import numpy as np
model=BernoulliNB()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

accuracy=accuracy_score(y_pred,y_test)
print(f"Accuracy: {accuracy:}")

claasification_rep=classification_report(y_test,y_pred,zero_division=0)
print("classification report:\n",claasification_rep)

Accuracy: 0.10108303249097472
classification report:
               precision    recall  f1-score   support

           3       0.00      0.00      0.00        18
           4       0.00      0.00      0.00        19
           5       0.00      0.00      0.00        22
           6       0.00      0.00      0.00        20
           7       0.00      0.00      0.00        16
           8       0.00      0.00      0.00        20
           9       0.00      0.00      0.00        20
          10       0.00      0.00      0.00        13
          11       0.00      0.00      0.00        20
          12       0.00      0.00      0.00        19
          13       0.00      0.00      0.00        24
          14       0.00      0.00      0.00        20
          15       0.10      1.00      0.18        28
          16       0.00      0.00      0.00        18

    accuracy                           0.10       277
   macro avg       0.01      0.07      0.01       277
weighted avg       0.01      0.10      0.02       277

DECISION TREE CLASSIFIER

In [82]:
from sklearn.tree import DecisionTreeClassifier # Make sure to import the DecisionTreeClassifier class
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


model=DecisionTreeClassifier()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

accuracy=accuracy_score(y_pred,y_test)
print(f"Accuracy: {accuracy:}")

claasification_rep=classification_report(y_test,y_pred,zero_division=0)
print("classification report:\n",claasification_rep)

Accuracy: 1.0
classification report:
               precision    recall  f1-score   support

           3       1.00      1.00      1.00        18
           4       1.00      1.00      1.00        19
           5       1.00      1.00      1.00        22
           6       1.00      1.00      1.00        20
           7       1.00      1.00      1.00        16
           8       1.00      1.00      1.00        20
           9       1.00      1.00      1.00        20
          10       1.00      1.00      1.00        13
          11       1.00      1.00      1.00        20
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        24
          14       1.00      1.00      1.00        20
          15       1.00      1.00      1.00        28
          16       1.00      1.00      1.00        18

    accuracy                           1.00       277
   macro avg       1.00      1.00      1.00       277
weighted avg       1.00      1.00      1.00       277

In [ ]:
from sklearn.svm import SVC
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = SVC(kernel='linear')
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:}")

classification_rep = classification_report(y_test, y_pred, zero_division=0)
print("classification report:\n", classification_rep)